feat: add docker role support
vexxhost/ansible-collection-containers pull request #5
Opened 2023-11-21 13:25 UTC by ricolin

2023-11-23 18:08 UTC, mnaser requested changes

2023-11-23 18:08 UTC, mnaser commented on roles/docker/templates/docker.socket.j2
We should use the exact file 1:1

https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.socket

I see `SocketGroup` is set to `docker` there, so we should do the same.  If the group is missing, we should create a `docker` group.

Also, we should move this into `files` instead of `templates` because no templating is happening here.

2023-11-23 18:08 UTC, mnaser commented on roles/docker/templates/docker.service.j2
Let's replace all of this file with the exact contents of https://github.com/moby/moby/blob/master/contrib/init/systemd/docker.service

and also move to files instead of template since this is not templated

2023-11-23 18:08 UTC, mnaser commented on roles/docker/tasks/main.yml
> +    dest: "{{ docker_cfg_file }}"
We should just use copy with contents and use the same pattern of having base vars for the role in vars/main.yml which are called `_docker_config` and then `docker_config: {}` and then recrusively merge them and just make contents to be `{{ _docker_config | combine(docker_config, recursive=True) | to_nice_json }}`

or something like that, so we dont need the template file anymore.

2023-11-23 18:08 UTC, mnaser commented on roles/docker/templates/daemon.json.j2
> +    "log-driver": "json-file",
default, we can drop this

2023-11-23 18:08 UTC, mnaser commented on roles/docker/templates/daemon.json.j2
Let's review this and compare to https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file and anything that's default we should just remove

2023-11-23 18:08 UTC, mnaser commented on roles/docker/defaults/main.yml
> +docker_limit_mem_lock: "infinity"
we can clean those up and reduce those since we are offering `docker_config` as a configure API

2023-11-24 06:30 UTC, ricolin commented on roles/docker/meta/main.yml
> +  - role: runc
maybe the issue I was faced is because I put `containerd` dependency after role: download_artifact?

2023-11-24 07:32 UTC, ricolin commented on roles/docker/meta/main.yml
> +  - role: runc
yep, it's because I put on the wrong order for roles here

2023-11-24 15:52 UTC, mnaser approved these changes

2023-11-24 15:53 UTC, merged